apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: nginx
    region: test
  name: nginx-test
spec:
  nodeSelector: 
    region: test
  containers:
  - env:
    - name: PROFILE
      value: TEST
    - name: DB_URL
      value: URL
    image: nginx
    name: nginx-test
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
