apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  namespace: vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /var/logs
