apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /var/logs
